
version: '2.0'
services:
  web:
    image: ankolodz/io-lab-docker-ci-public
    ports:
	- 5000:5000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
        volumes: 
	- ./data:/data:z
